apiVersion: skaffold/v2beta17
kind: Config
metadata:
  name: micronaut-book-vue
build:
  artifacts:
  - image: faruryo/micronaut-book-vue
    docker:
      dockerfile: Dockerfile
  local:
    useBuildkit: true
deploy:
  kubectl:
    manifests:
    - kubernetes/vue.yaml
portForward:
- resourceType: service
  resourceName: book-vue
  port: 80
  localPort: 8081
profiles:
- name: dev
  build:
    artifacts:
    - image: faruryo/micronaut-book-vue-dev
      sync:
        infer:
        - public/**/*
        - src/**/*
      docker:
        dockerfile: Dockerfile-dev
  deploy:
    kubectl:
      manifests:
      - kubernetes/vue-dev.yaml
