apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: micronaut-book-vue
build:
  artifacts:
    - image: faruryo/micronaut-book-vue
  local: {}
deploy:
  kubectl:
    manifests:
      - kubernetes/vue.yaml
      - kubernetes/api.yaml
      - kubernetes/mysql.yaml
portForward:
  - resourceType: service
    resourceName: book-vue
    port: 80
    localPort: 8081
