---
# vueとapiをさばくためのnginx
apiVersion: v1
kind: Service
metadata:
  name: book-vue
spec:
  selector:
    app: book-vue
  ports:
    - name: http
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: book-vue
  name: book-vue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-vue
  template:
    metadata:
      labels:
        app: book-vue
    spec:
      containers:
        - name: book
          image: nginx:stable-alpine
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "100m"
          volumeMounts:
            - name: conf
              mountPath: /etc/nginx/conf.d/
      volumes:
        - name: conf
          configMap:
            name: nginx-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |-
    upstream book-api {
        server book-api;
    }

    upstream book-vue-dev {
        server book-vue-dev;
    }

    server {
        listen 80;

        location /book {
            proxy_pass http://book-api;
        }

        location / {
            proxy_pass http://book-vue-dev;
        }
    }

---
# webpack DevServer
apiVersion: v1
kind: Service
metadata:
  name: book-vue-dev
spec:
  selector:
    app: book-vue-dev
  ports:
    - name: http
      port: 80
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: book-vue-dev
  name: book-vue-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-vue-dev
  template:
    metadata:
      labels:
        app: book-vue-dev
    spec:
      containers:
        - name: book
          image: faruryo/micronaut-book-vue-dev
          imagePullPolicy: Never
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
