---
apiVersion: v1
kind: Service
metadata:
  name: book-vue
spec:
  selector:
    app: book-vue
  ports:
    - name: http
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: book-vue
  name: book-vue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-vue
  template:
    metadata:
      labels:
        app: book-vue
    spec:
      containers:
        - name: book
          image: faruryo/micronaut-book-vue
          imagePullPolicy: Never
          env:
            - name: MICRONAUT_ENVIRONMENTS
              value: local
          envFrom:
            - configMapRef:
                name: mysql-env
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "100m"
          readinessProbe:
            httpGet:
              port: 80
              path: /
            failureThreshold: 2
            periodSeconds: 3
          volumeMounts:
            - name: conf
              mountPath: /etc/nginx/conf.d/
      volumes:
        - name: conf
          configMap:
            name: nginx-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |-
    upstream book-api {
        server book-api;
    }

    server {
        listen 80;

        location /book {
            proxy_pass http://book-api;
        }
    }
