name: release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: hadolint
        uses: burdzwastaken/hadolint-action@master

      - name: Dockerイメージをビルド&プッシュ
        id: publish_docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: faruryo/micronaut-book-vue
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          snapshot: true
